services:
  backend:
    build:
      context: ./backend
    ports:
      - "3012:8000" # Mappe 8000 (conteneur) à 3012 (serveur)
    environment:
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      - db
    restart: always

  frontend:
    build:
      context: ./frontend
    ports:
      - "3014:80" # Serve l'app Vite sur le port 3014
    restart: always

  db:
    image: mariadb:10.6
    ports:
      - "3013:3306" # Mappe 3306 (conteneur) à 3013 (serveur)
    environment:
      MARIADB_ROOT_PASSWORD: root_password
      MARIADB_DATABASE: my_database
      MARIADB_USER: my_username
      MARIADB_PASSWORD: my_password
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
